/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSuppliersRouteImport } from './routes/_authenticated/app.suppliers'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppRequestsRouteImport } from './routes/_authenticated/app.requests'
import { Route as AuthenticatedAppPurchaseOrdersRouteImport } from './routes/_authenticated/app.purchase-orders'
import { Route as AuthenticatedAppMovementsRouteImport } from './routes/_authenticated/app.movements'
import { Route as AuthenticatedAppLocationsRouteImport } from './routes/_authenticated/app.locations'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/app.help'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppCatalogRouteImport } from './routes/_authenticated/app.catalog'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppAiInsightsRouteImport } from './routes/_authenticated/app.ai-insights'

const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSuppliersRoute =
  AuthenticatedAppSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRequestsRoute =
  AuthenticatedAppRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPurchaseOrdersRoute =
  AuthenticatedAppPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMovementsRoute =
  AuthenticatedAppMovementsRouteImport.update({
    id: '/movements',
    path: '/movements',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLocationsRoute =
  AuthenticatedAppLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCatalogRoute = AuthenticatedAppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiInsightsRoute =
  AuthenticatedAppAiInsightsRouteImport.update({
    id: '/ai-insights',
    path: '/ai-insights',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/app/ai-insights': typeof AuthenticatedAppAiInsightsRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/catalog': typeof AuthenticatedAppCatalogRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/locations': typeof AuthenticatedAppLocationsRoute
  '/app/movements': typeof AuthenticatedAppMovementsRoute
  '/app/purchase-orders': typeof AuthenticatedAppPurchaseOrdersRoute
  '/app/requests': typeof AuthenticatedAppRequestsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/ai-insights': typeof AuthenticatedAppAiInsightsRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/catalog': typeof AuthenticatedAppCatalogRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/locations': typeof AuthenticatedAppLocationsRoute
  '/app/movements': typeof AuthenticatedAppMovementsRoute
  '/app/purchase-orders': typeof AuthenticatedAppPurchaseOrdersRoute
  '/app/requests': typeof AuthenticatedAppRequestsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/app/ai-insights': typeof AuthenticatedAppAiInsightsRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/catalog': typeof AuthenticatedAppCatalogRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/locations': typeof AuthenticatedAppLocationsRoute
  '/_authenticated/app/movements': typeof AuthenticatedAppMovementsRoute
  '/_authenticated/app/purchase-orders': typeof AuthenticatedAppPurchaseOrdersRoute
  '/_authenticated/app/requests': typeof AuthenticatedAppRequestsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup-admin'
    | '/app'
    | '/auth/callback'
    | '/app/ai-insights'
    | '/app/analytics'
    | '/app/catalog'
    | '/app/dashboard'
    | '/app/help'
    | '/app/locations'
    | '/app/movements'
    | '/app/purchase-orders'
    | '/app/requests'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup-admin'
    | '/auth/callback'
    | '/app/ai-insights'
    | '/app/analytics'
    | '/app/catalog'
    | '/app/dashboard'
    | '/app/help'
    | '/app/locations'
    | '/app/movements'
    | '/app/purchase-orders'
    | '/app/requests'
    | '/app/settings'
    | '/app/suppliers'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/setup-admin'
    | '/_authenticated/app'
    | '/auth/callback'
    | '/_authenticated/app/ai-insights'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/catalog'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/help'
    | '/_authenticated/app/locations'
    | '/_authenticated/app/movements'
    | '/_authenticated/app/purchase-orders'
    | '/_authenticated/app/requests'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/suppliers'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupAdminRoute: typeof SetupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/suppliers': {
      id: '/_authenticated/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AuthenticatedAppSuppliersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/requests': {
      id: '/_authenticated/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AuthenticatedAppRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/purchase-orders': {
      id: '/_authenticated/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AuthenticatedAppPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/movements': {
      id: '/_authenticated/app/movements'
      path: '/movements'
      fullPath: '/app/movements'
      preLoaderRoute: typeof AuthenticatedAppMovementsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/locations': {
      id: '/_authenticated/app/locations'
      path: '/locations'
      fullPath: '/app/locations'
      preLoaderRoute: typeof AuthenticatedAppLocationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/catalog': {
      id: '/_authenticated/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AuthenticatedAppCatalogRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai-insights': {
      id: '/_authenticated/app/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/ai-insights'
      preLoaderRoute: typeof AuthenticatedAppAiInsightsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiInsightsRoute: typeof AuthenticatedAppAiInsightsRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppCatalogRoute: typeof AuthenticatedAppCatalogRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppLocationsRoute: typeof AuthenticatedAppLocationsRoute
  AuthenticatedAppMovementsRoute: typeof AuthenticatedAppMovementsRoute
  AuthenticatedAppPurchaseOrdersRoute: typeof AuthenticatedAppPurchaseOrdersRoute
  AuthenticatedAppRequestsRoute: typeof AuthenticatedAppRequestsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSuppliersRoute: typeof AuthenticatedAppSuppliersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiInsightsRoute: AuthenticatedAppAiInsightsRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppCatalogRoute: AuthenticatedAppCatalogRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppLocationsRoute: AuthenticatedAppLocationsRoute,
  AuthenticatedAppMovementsRoute: AuthenticatedAppMovementsRoute,
  AuthenticatedAppPurchaseOrdersRoute: AuthenticatedAppPurchaseOrdersRoute,
  AuthenticatedAppRequestsRoute: AuthenticatedAppRequestsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSuppliersRoute: AuthenticatedAppSuppliersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupAdminRoute: SetupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
